name: ScriptExec
main: fr.utrosh.pterobypass.ScriptPlugin
version: 0.1.0
authors: [UTrosh]
description: Makes scripts executable from Minecraft. Scripts must reside in the plugin folder and be executable.


commands:
  sh:
    description: runs a script
    usage: /sh [script] [arg1] [arg2] ...
    permission: script.command
  bsh:
    description: runs a script but clocks further execution until script exited
    usage: /bsh [script] [arg1] [arg2] ...
    permission: script.command
permissions:
  script.*:
    description: Gives access to all script commands
    children:
      script.command: true
